### ISSUE TITLE
[Bug] Missing files

### ISSUE THREAD

**Issue by kiber-io** [YT-Advanced/WSA-Script#1199] opened 2024-01-19 11:24 UTC
### Steps to reproduce

Issue: https://github.com/YT-Advanced/WSA-Script/issues/1198

### Expected behaviour

Successful installation

### Actual behaviour

These files are missing from the final archive:
WSACrashUploader\arm64\KernelTraceControl.dll
WSACrashUploader\arm64\msvcp140.dll
WSACrashUploader\arm64\vcruntime140.dll
WSACrashUploader\arm64\msdia140.dll

otherwise, the installation error:
```
C:\WSA\Install.ps1 :
Some files are missing in the folder.
Please try to build again.
Press any key to exit
```

### Windows version

Windows 11, 22H2, 22621.2134

### Version requirement

- [X] I am using latest commit of WSA-Script commit

**Comment by YT-Advanced** [comment] 2024-01-19 11:57
Have you tried redownload then reinstall again

**Comment by YT-Advanced** [comment] 2024-01-19 11:58
@kiber-io Also please update your zip extractor to the latest version

**Comment by kiber-io** [comment] 2024-01-19 14:10
Hmm, there really was a mistake when unpacking. I didn't pay attention to her at first :D
```
Unsupported compression method: WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-a0b8aa4d-alpha-2-stable-MindTheGapps-13.0-as-Pixel-7-RemovedAmazon\WSACrashUploader\arm64\KernelTraceControl.dll
Unsupported compression method: WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-a0b8aa4d-alpha-2-stable-MindTheGapps-13.0-as-Pixel-7-RemovedAmazon\WSACrashUploader\arm64\msdia140.dll
Unsupported compression method: WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-a0b8aa4d-alpha-2-stable-MindTheGapps-13.0-as-Pixel-7-RemovedAmazon\WSACrashUploader\arm64\msvcp140.dll
Unsupported compression method: WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-a0b8aa4d-alpha-2-stable-MindTheGapps-13.0-as-Pixel-7-RemovedAmazon\WSACrashUploader\arm64\vcruntime140.dll
```
There was a version 7z 21.07, updated to the latest - successfully unpacked. Magic.

**Comment by kiber-io** [comment] 2024-01-19 14:11
However, the installation still fails:
```
C:\WSA > .\Install.ps1 The operation has been completed successfully.
Installing MicrosoftCorporationII.WindowsSubsystemForAndroid version: 2311.40000.5.0
Dependency package Microsoft.UI.Xaml.2.8 x64 current version: 8.2305.5001.0.
Nothing to do.
Dependency package Microsoft.VCLibs.140.00.UWPDesktop x64 current version: 14.0.32530.0.
Nothing to do.
Dependency package Microsoft.VCLibs.140.00 x64 current version: 14.0.32530.0.
Nothing to do.

Installing MagiskOnWSA...
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package registration failed.
AppxManifest.xml (85, 27): error 0x80073B06: The Microsoft Corporation package cannot be installed or updated.WindowsSub
systemForAndroid_8wekyb3d8bbwe, since it is impossible to determine the splash screen image for the current
application context. The application context may include a specific language, dots per inch, contrast, or other conditions.
Add an image that will be used by default if the splash screen image cannot be determined
 for a specific context.
```

**Comment by YT-Advanced** [comment] 2024-01-19 14:21
I think you don't need xD. Can you check this guide:
https://github.com/YT-Advanced/WSA-Script/blob/main/docs/Fixes/Fix%20Error%200x80073CF6.md

**Comment by kiber-io** [comment] 2024-01-19 14:31
Well, actually, there is nothing new in that guide to correct the error. So it's still present, and GetAppxLog doesn't have anything useful at first glance, it's still the same error. Log file is attached, but my system is in Russian, which is why the logs are also written in Russian (what an ingenious solution, thanks to microsoft!)
[logs_ru.txt](https://github.com/YT-Advanced/WSA-Script/files/13990459/logs_ru.txt)

**Comment by YT-Advanced** [comment] 2024-01-20 14:28
Hi, can you check this prebuilt version. Thanks !
https://github.com/YT-Advanced/WSA-Script/actions/runs/7594966619

**Comment by kiber-io** [comment] 2024-01-22 10:36
It has been installed, but it is always loading when turned on. The same behavior happened when I tried to build MagiskOnWSALocal myself specifically with Magisk Alpha. It worked with Delta, but not with Alpha. I thought maybe your repository would work :)
![изображение](https://github.com/YT-Advanced/WSA-Script/assets/60169133/54c19e7a-8d11-4336-b61c-a7b9426f9cd9)

**Comment by YT-Advanced** [comment] 2024-01-22 10:53
Hmm so you mean that Magisk Alpha is not compatiable with WSA ?

**Comment by kiber-io** [comment] 2024-01-22 11:00
I'm not sure about this, but based on the fact that with the same settings, wsa runs with regular magisk and magisk delta and does not run with Alpha - apparently incompatible.
It is quite possible that some additional settings are needed for Alpha

**Comment by LordArrin** [comment] 2024-03-29 13:28
<img width="704" alt="image" src="https://github.com/YT-Advanced/WSA-Script/assets/79581469/1509bdf2-5a17-42a5-83f0-169535927b8e">
doesnt work with kernelsu

**Comment by zyc120** [comment] 2024-06-11 07:24
It's not a bug,your 7z ver old.
Update your 7z from https://www.7-zip.org/download.html and it's worked.

**Comment by ygiveupc** [comment] 2024-06-11 08:57
is 7zip version

**Comment by bjl101501** [comment] 2024-06-18 04:30
Check and modify the file names in filelist.txt. Delete the redundant ones or copy them from the compressed package of other versions.

**Comment by LordArrin** [comment] 2024-06-19 04:38
I have a latest version of 7zip. Just went to another's  dev repo.

**Comment by TriDefender** [comment] 2024-07-21 11:48
> Have you tried redownload then reinstall again

Yes I had the same issue, the checksums for Magisk just dont match, the kernelsu one matched alright but it still reported such an error. I tested the decompression with winrar, problem persists

**Comment by YT-Advanced** [comment] 2024-07-21 12:02
> > Have you tried redownload then reinstall again
> 
> Yes I had the same issue, the checksums for Magisk just dont match, the kernelsu one matched alright but it still reported such an error. I tested the decompression with winrar, problem persists

can you check `filelist.txt` to see which file is missing please

**Comment by TriDefender** [comment] 2024-07-21 12:13
> > > Have you tried redownload then reinstall again
> > 
> > 
> > Yes I had the same issue, the checksums for Magisk just dont match, the kernelsu one matched alright but it still reported such an error. I tested the decompression with winrar, problem persists
> 
> can you check `filelist.txt` to see which file is missing please

Something called APEX, can't quite locate the file or folder, deleting the filecheck will result in crashes, however I had some luck [here](https://github.com/YT-Advanced/WSA-Script/actions/runs/9958430231).

**Comment by YT-Advanced** [comment] 2024-07-22 02:44
> Something called APEX, can't quite locate the file or folder, deleting the filecheck will result in crashes, however I had some luck [here](https://github.com/YT-Advanced/WSA-Script/actions/runs/9958430231).

Thanks. @s1204IT Hmm, seem like gapps was not merged correctly

**Comment by YT-Advanced** [comment] 2024-07-22 03:03
@TriDefender Can you provide additational information, like which file have you downloaded that occur the error or your system information

**Comment by TriDefender** [comment] 2024-07-22 12:17
> @TriDefender Can you provide additational information, like which file have you downloaded that occur the error or your system information

Every archive for X86 under this link seems to have same error

**Comment by likertuban** [comment] 2024-12-25 11:46
open filelist.txt
then remove this line, and save and run run.bat again :
apex
apex\\.gitkeep

**Closed** 2024-12-29 02:13 UTC
Labels: bug
